name: Deployment

on:
    push:
        branches:
            - 'root'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repository
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  fetch-depth: 0
                  path: './lua'
            - name: Checkout docs website repository
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  fetch-depth: 0
                  repository: paygammy/simple-spy-paygammy
                  path: './website'
                  token: ${{ secrets.NICK_PERSONAL_TOKEN }}
            - name: build scripts
              uses: ./lua/.github/actions/bundle
              with:
                  source: ./lua/src
                  output: ./lua/dist
            - name: parse scripts
              uses: ./lua/.github/actions/get-metadata
              with:
                  source: ./lua/src
                  output: ./website/src/lib/lib/script-data.json
            - name: Generate the docs
              uses: finale-lua/lua-docs-generator@1.3.1
              with:
                  input: './lua/src/mixin'
                  repositoryUrl: 'https://github.com/paygammy/simple-spy-paygammy/tree/root/scripts'
                  output: './lua/docs/mixin'
            - run: 'rm -rf website/docs'
            - run: 'cp -R lua/docs website/docs'
            - name: Commit & Push docs to website
              uses: actions-js/push@v1.3
              with:
                  github_token: ${{ secrets.NICK_PERSONAL_TOKEN }}
                  directory: website
                  branch: main
                  repository: paygammy/simple-spy-paygammy
            - name: Commit & Push docs to this repo
              uses: actions-js/push@v1.3
              with:
                  github_token: ${{ secrets.NICK_PERSONAL_TOKEN }}
                  directory: lua
                  branch: root
